language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t snly2386/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true snly2386/react-test npm run test -- --coverage

after_success:
  - docker build -t snly2386/multip-client ./client
  - docker build -t snly2386/multip-worker ./worker
  - docker build -t snly2386/multip-server ./server
  - docker build -t snly2386/multip-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 
  - docker push snly2386/multip-client
  - docker push snly2386/multip-worker
  - docker push snly2386/multip-server
  - docker push snly2386/multip-nginx

deploy:
  # edge: true
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  provider: elasticbeanstalk
  bucket_name: elasticbeanstalk-us-east-1-311342128241
  bucket_path: multi-container
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET
  

